#!/bin/bash

set -e

if [ -z $INTERNALCALL ];then
    echo "This script should not be called by you. Thanks for calling."
    exit 1
fi


PATH=$CC_DIR:$PATH

if [ -f $CONFIG ];then
    . $CONFIG
else
    echo "$CONFIG does not exist. Can't continue"
    exit 1
fi

. $CC_DIR/init-variables
# Reexport variables
export DISK_ID
export CONFIG
export TMP
export CC_DIR
export PATH
export INTERNALCALL

export VARIANT
export DIST
export MIRROR
export SCRIPT
export COMPONENTS
export PACKAGES
export KERNEL
export SQUASHFS
export ISOLINUX
export ISOLINUX_PATH
export CDVOLUME
export LIVE_PACKAGES
export LIVE_SYSTEM
export MAX_SIZE

check_variable DISK_ID 


mkdir -p $TMP/$DISK_ID-publish
for ARCH in $ARCHS;do
    export ARCH=$ARCH
    echo "Building ISO for $ARCH $DIST"
    . $CC_DIR/functions
    $CC_DIR/debootstrap
    $CC_DIR/install-system
    $CC_DIR/squashfs
    $CC_DIR/isolinux
    $CC_DIR/genisoimage

    list_rootfs_packages_to_file $TMP/$DISK_ID-publish/$DIST-$VARIANT-$ARCH.list
done
