#!/bin/bash

set -e

if [ -z $INTERNALCALL ];then
    echo "This script should not be called by you. Thanks for calling."
    exit 1
fi

. $CC_DIR/functions

check_variable DISK_MOUNTED
check_variable DISK_ORIGINAL

# Create the mount places
mkdir -p $TMP/$DISK_MOUNTED

echo "Mounting the image $DISK_ORIGINAL to $TMP/$DISK_MOUNTED"
mount -o loop $DISK_ORIGINAL $TMP/$DISK_MOUNTED

echo "Copying the image's content"
cp -a $TMP/$DISK_MOUNTED $DISK

# unmount and remove the mount locations
umount $TMP/$DISK_MOUNTED
rmdir $TMP/$DISK_MOUNTED
