#!/bin/bash

set -e

if [ -z $INTERNALCALL ];then
    echo "This script should not be called by you. Thanks for calling."
    exit 1
fi

. $CC_DIR/functions

check_variable ARCH
check_variable DIST
check_variable MIRROR
check_variable DISK_ID
check_variable SCRIPT

echo "Debootstrap to $DIST"
if [ "x$NO_CHECK_GPG" != "x" ];then
    echo "Not checking GPG"
    NO_CHECK_GPG="--no-check-gpg"
fi
/usr/sbin/debootstrap --arch $ARCH $NO_CHECK_GPG $DIST $ROOTFS $MIRROR $SCRIPT

# Inject DIST_ID into lsb-release
R=`grep DISTRIB_RELEASE $(pwd)/lsb-release`; Y="-$DISK_ID"
cat /etc/lsb-release | sed -e "s/$R/$R$Y/g" > $ROOTFS/etc/lsb-release.tmp 
mv $ROOTFS/etc/lsb-release.tmp $ROOTFS/etc/lsb-release


