#!/bin/bash

set -e

if [ -z $INTERNALCALL ];then
    echo "This script should not be called by you. Thanks for calling."
    exit 1
fi

. $CC_DIR/functions

check_variable DISK_MOUNTED
check_variable DISK_ORIGINAL

# Create the mount places
mkdir -p $TMP/$DISK_MOUNTED
mkdir -p $TMP/$ROOTFS_MOUNTED

echo "Mounting the image $DISK_ORIGINAL to $TMP/$DISK_MOUNTED"
mount -o loop $DISK_ORIGINAL $TMP/$DISK_MOUNTED

echo "Copying the image's content"
cp -a $TMP/$DISK_MOUNTED $DISK

# Mount the rootfs
mount -o loop $TMP/$DISK_MOUNTED/live/filesystem.squashfs $TMP/$ROOTFS_MOUNTED

# Copy the rootfs's content
echo "Extracting image's content"
cp -a $TMP/$ROOTFS_MOUNTED $ROOTFS

# unmount and remove the moount locations
umount $TMP/$ROOTFS_MOUNTED
umount $TMP/$DISK_MOUNTED
rmdir $TMP/$DISK_MOUNTED
rmdir $TMP/$ROOTFS_MOUNTED
