#!/bin/bash

set -e

if [ -z $INTERNALCALL ];then
    echo "This script should not be called by you. Thanks for calling."
    exit 1
fi

. $CC_DIR/functions

check_variable CDVOLUME
check_variable ARCH
check_variable DIST
check_variable VARIANT

ISOOPT="-v -A BlankOnCDFactory -p BlankOn -publisher BlankOn -V $CDVOLUME"
ISOOPT="$ISOOPT -no-emul-boot -boot-load-size 4 -boot-info-table"
if [ -n "$ISOLINUX" ]; then
    ISOOPT="$ISOOPT -r -b isolinux/isolinux.bin -c isolinux/boot.cat"
else
    mkdir -p $DISK/boot/grub
    cat << @EOF > $TMP/temp.cfg
set prefix=/boot
configfile /boot/grub/grub.cfg
@EOF
    grub-mkimage -p /boot -o $TMP/core.img -O i386-pc biosdisk iso9660 linux configfile -c $TMP/temp.cfg
    cat /usr/lib/grub/i386-pc/cdboot.img $TMP/core.img > $DISK/boot/grub/eltorito.img
    cat << @EOF > $DISK/boot/grub/grub.cfg
set timeout=0
set default=0 # Set the default menu entry
 
menuentry "Live" {
    linux /boot/vmlinuz boot=live config
    initrd /boot/initrd.img
    boot
}

@EOF

    if [ -n "$D_I_URL" ];then
    cat << @EOF >> $DISK/boot/grub/grub.cfg
menuentry "Install" {
    linux /install/gtk/vmlinuz  video=vesa:ywrap,mtrr vga=788 quiet
    initrd /install/gtk/initrd.gz
    boot
}

@EOF
    fi
    ISOOPT="$ISOOPT -R -b boot/grub/eltorito.img"
fi

mkdir -p $DISK/.disk
echo "$CDVOLUME $DIST ($DISK_ID)" > $DISK/.disk/info
echo "full_cd/single" > $DISK/.disk/cd_type
touch $DISK/.disk/base_installable

# Generates the iso image
pushd $TMP
genisoimage ${ISOOPT} -o $DIST-$VARIANT-$ARCH.iso -J -l -cache-inodes -allow-multidot $DISK_BUILD
popd

if [ -n $MAX_SIZE_BYTE -a $MAX_SIZE_BYTE -gt 0 -a -f $DIST-$VARIANT-$ARCH.iso ];then
    A=`du -b $DIST-$VARIANT-$ARCH.iso |cut -f1`
    if [ $A -gt $MAX_SIZE_BYTE ];then
        touch $DIST-$VARIANT-$ARCH.iso.OVERSIZED
    fi
fi

md5sum $TMP/$DIST-$VARIANT-$ARCH.iso > $TMP/$DIST-$VARIANT-$ARCH.iso.md5sum
mv $TMP/$DIST-$VARIANT-$ARCH.iso* $TMP/$DISK_ID-publish
