#!/bin/bash

set -e

if [ -z $INTERNALCALL ];then
    echo "This script should not be called by you. Thanks for calling."
    exit 1
fi

. $CC_DIR/functions

do_chroot /usr/bin/lsb_release -d -s > /tmp/distro-id
read DISTRO_ID < /tmp/distro-id
rm -f /tmp/distro-id

mkdir -p $DISK/boot/grub
cat << @EOF > $TMP/temp.cfg
set prefix=/boot
configfile /boot/grub/grub.cfg
@EOF
    cp $CC_DIR/blobs/eltorito.img $DISK/boot/grub/
    cat << @EOF > $DISK/boot/grub/grub.cfg
set timeout=0
set default=0 # Set the default menu entry
 
menuentry "$DISTRO_ID" --class gnu-linux {
    linux /boot/vmlinuz boot=live config
    initrd /boot/initrd.img
    boot
}

@EOF


