#!/bin/bash

set -e

if [ -z $INTERNALCALL ];then
    echo "This script should not be called by you. Thanks for calling."
    exit 1
fi

. $CC_DIR/functions

do_chroot /usr/bin/lsb_release -d -s > /tmp/distro-id
read DISTRO_ID < /tmp/distro-id
rm -f /tmp/distro-id

mkdir -p $DISK/boot/grub
cat << @EOF > $TMP/temp.cfg
set prefix=/boot
configfile /boot/grub/grub.cfg
@EOF
    grub-mkimage -p /boot -o $TMP/core.img -O i386-pc biosdisk iso9660 linux configfile -c $TMP/temp.cfg
    cat /usr/lib/grub/i386-pc/cdboot.img $TMP/core.img > $DISK/boot/grub/eltorito.img
    cat << @EOF > $DISK/boot/grub/grub.cfg
set timeout=0
set default=0 # Set the default menu entry
 
menuentry "$DISTRO_ID" --class gnu-linux {
    linux /boot/vmlinuz boot=live config
    initrd /boot/initrd.img
    boot
}

@EOF


