#!/bin/bash

set -e

check_variable() {
    eval X="\$$1"
    if [ -z "$X" ];then
        echo "Error $1 variable is not specified."
        exit
    fi
}


LC_ALL=C
LANG=C
DISK_MOUNTED=$DISK_ID-mounted
ROOTFS_MOUNTED=$DISK_ID-rootfs-mounted
DISK_BUILD=$DISK_ID-disk-$ARCH
ROOTFS_BUILD=$DISK_ID-rootfs-$ARCH

ROOTFS=$TMP/$ROOTFS_BUILD
DISK=$TMP/$DISK_BUILD
unset MOUNTS

DIVERTS="usr/sbin/mkinitrd usr/sbin/invoke-rc.d /sbin/start-stop-daemon" 

export DEBIAN_FRONTEND=noninteractive 
export DEBCONF_NONINTERACTIVE_SEEN=true

check_variable DISK_ID
check_variable TMP 
