#!/bin/bash
if [ -n "$DEBUG" ];then
    set -x
fi

set -e

check_variable() {
    eval X="\$$1"
    if [ -z "$X" ];then
        echo "Error $1 variable is not specified."
        exit
    fi
}


export LC_ALL=C
export LANG=C
export DISK_MOUNTED=$DISK_ID-mounted
export ROOTFS_MOUNTED=$DISK_ID-rootfs-mounted
export DISK_BUILD=$DISK_ID-disk-$ARCH
export ROOTFS_BUILD=$DISK_ID-rootfs-$ARCH

export ROOTFS=$TMP/$ROOTFS_BUILD
export DISK=$TMP/$DISK_BUILD
unset MOUNTS

export DIVERTS="usr/sbin/invoke-rc.d /sbin/start-stop-daemon" 

export DEBIAN_FRONTEND=noninteractive 
export DEBCONF_NONINTERACTIVE_SEEN=true
export LOCAL_REPO_PATH=/lib/live/mount/medium/repo

if [ -n $MAX_SIZE ];then
    export MAX_SIZE_BYTE=`echo "$MAX_SIZE * 1024 * 1024"|bc`
fi

check_variable DISK_ID
check_variable TMP 
