#!/bin/bash

set -e

check_variable() {
    eval X="\$$1"
    if [ -z "$X" ];then
        echo "Error $1 variable is not specified."
        exit
    fi
}


export LC_ALL=C
export LANG=C
export DISK_MOUNTED=$DISK_ID-mounted
export ROOTFS_MOUNTED=$DISK_ID-rootfs-mounted
export DISK_BUILD=$DISK_ID-disk-$ARCH
export ROOTFS_BUILD=$DISK_ID-rootfs-$ARCH

export ROOTFS=$TMP/$ROOTFS_BUILD
export DISK=$TMP/$DISK_BUILD
unset MOUNTS

export DIVERTS="usr/sbin/mkinitrd usr/sbin/invoke-rc.d /sbin/start-stop-daemon" 

export DEBIAN_FRONTEND=noninteractive 
export DEBCONF_NONINTERACTIVE_SEEN=true

if [ -n $MAX_SIZE ];then
    export MAX_SIZE_BYTE=`$MAX_SIZE \* 1024 \* 1024`
fi

check_variable DISK_ID
check_variable TMP 
