#!/bin/bash

set -e

if [ -z $INTERNALCALL ];then
    echo "This script should not be called by you. Thanks for calling."
    exit 1
fi

. $CC_DIR/functions

check_variable DIST
check_variable MIRROR
check_variable DISK_ID
check_variable COMPONENTS
check_variable PACKAGES
check_variable KERNEL 
check_variable LIVE_SYSTEM 

cat << @@EOF > $ROOTFS/etc/apt/sources.list
deb $MIRROR $DIST $COMPONENTS 
@@EOF

if [ -n "$EXTRA_REPOSITORY" ];then
    echo $EXTRA_REPOSITORY | sed -e 's/|/\n/g'> $ROOTFS/etc/apt/sources.list.d/extra.list
fi

if [ -n "$EXTRA_REPOSITORY_HIDDEN" ];then
    echo $EXTRA_REPOSITORY_HIDDEN | sed -e 's/|/\n/g'> $ROOTFS/etc/apt/sources.list.d/hidden.list
fi
set -x
eval "KERNEL_ARCH=`eval "echo \\\$KERNEL_$ARCH"`"
if [ -z "$KERNEL_ARCH" ];then
    KERNEL_ARCH=$KERNEL
fi
refresh_repository
install_package $PACKAGES $KERNEL_ARCH

if [ -n "$BLACKLIST" ];then
    remove_package $BLACKLIST
fi

# Remove hostname so it will be configured by live-config
rm -f $ROOTFS/etc/hostname

mkdir -p $DISK/$LIVE_SYSTEM
printf $(du -sx --block-size=1 $ROOTFS | cut -f1) > $DISK/$LIVE_SYSTEM/filesystem.size
list_rootfs_packages_to_file $DISK/$LIVE_SYSTEM/filesystem.manifest

if [ $LIVE_SYSTEM = "live" ];then
    cat << @EOF > $DISK/$LIVE_SYSTEM/config.conf 
LIVE_HOSTNAME="blankon"
LIVE_USERNAME="blankon"
LIVE_USER_FULLNAME="BlankOn"
LIVE_USER_DEFAULT_GROUPS="sudo audio cdrom dip floppy video plugdev netdev powerdev scanner bluetooth debian-tor"
@EOF
fi

if [ -n "$LIVE_PACKAGES" ];then
    install_package $LIVE_PACKAGES
fi

if [ -z "$ISOLINUX" ];then
    mkdir -p $DISK/boot
    cp $ROOTFS/boot/initrd.img* $DISK/boot/initrd.img
    cp $ROOTFS/boot/vmlinuz* $DISK/boot/vmlinuz
else
    cp $ROOTFS/boot/initrd.img* $DISK/$LIVE_SYSTEM/initrd.img
    cp $ROOTFS/boot/vmlinuz* $DISK/$LIVE_SYSTEM/vmlinuz
fi

if [ -d $ROOTFS/etc/apt/sources.list.d/hidden.list ];then
    rm -f $ROOTFS/etc/apt/sources.list.d/hidden.list
    refresh_repository
fi
