#!/bin/bash

set -e

if [ -z $INTERNALCALL ];then
    echo "This script should not be called by you. Thanks for calling."
    exit 1
fi

. $CC_DIR/functions

check_variable ROOTFS
check_variable DISK_ID

#STRIP="/usr/share/doc /usr/share/locale/"
if [ -n "$STRIP" ];then 
    rm -f $TMP/$DISK_ID-stripped.list
    for i in $STRIP;do
        set +e
        grep -h "$i" $ROOTFS/var/lib/dpkg/info/*list >> $TMP/$DISK_ID-stripped.list
        set -e
    done
    echo "Truncating..."
    for i in `cat $TMP/$DISK_ID-stripped.list`;do
        if [ -f $ROOTFS/$i ];then
            echo $i
            rm -rf $ROOTFS/$i
            touch $ROOTFS/$i
        fi
    done
fi

if [ -n "$STRIP_EXCLUSIONS" ];then
    install_package "--reinstall $STRIP_EXCLUSIONS"
fi
